# Generated by Django 5.1.2 on 2025-07-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_userprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="file_context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="keywords",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
