# Generated by Django 5.1.2 on 2025-08-24 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_file_context_course_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedraft",
            name="exam_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="certificate_earned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="certificate_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="exam_attempts_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="exam_eligible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="last_exam_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CourseExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("default", "Default Exam Style"),
                            ("custom", "Custom Prompt"),
                            ("template", "Uploaded Template"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        help_text="Instructions for AI to generate exam",
                        null=True,
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        blank=True, null=True, upload_to="exam_templates/"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("time_limit_minutes", models.PositiveIntegerField(default=120)),
                ("passing_score", models.FloatField(default=70.0)),
                ("max_attempts", models.PositiveIntegerField(default=1)),
                ("structure", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam",
                        to="courses.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("practical", "Practical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                ("options", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.TextField(blank=True, null=True)),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.courseexam",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("grading", "Grading"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("flagged", "Flagged for Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("tab_switch_count", models.PositiveIntegerField(default=0)),
                ("fullscreen_exit_count", models.PositiveIntegerField(default=0)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="courses.courseexam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "exam")},
            },
        ),
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("max_score", models.FloatField()),
                ("percentage", models.FloatField()),
                ("passed", models.BooleanField()),
                ("graded_by_ai", models.BooleanField(default=True)),
                ("reviewed_by_instructor", models.BooleanField(default=False)),
                ("instructor_feedback", models.TextField(blank=True, null=True)),
                ("certificate_generated", models.BooleanField(default=False)),
                (
                    "certificate_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="courses.examsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProctorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tab_switch", "Tab Switch"),
                            ("fullscreen_exit", "Fullscreen Exit"),
                            ("face_not_visible", "Face Not Visible"),
                            ("multiple_faces", "Multiple Faces Detected"),
                            ("audio_detected", "Audio Detected"),
                            ("no_webcam", "Webcam Disconnected"),
                            ("system_check", "System Check"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctor_logs",
                        to="courses.examsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True, null=True)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("points_earned", models.FloatField(default=0)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.examquestion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="courses.examsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "question")},
            },
        ),
    ]
